@TransferFlow.Api_HostAddress = https://localhost:7134

### Health

GET {{TransferFlow.Api_HostAddress}}/health

### Health - Live

GET {{TransferFlow.Api_HostAddress}}/health/live

### Health - Ready

GET {{TransferFlow.Api_HostAddress}}/health/ready

### Create wallet

POST {{TransferFlow.Api_HostAddress}}/wallets

### Get wallet

GET {{TransferFlow.Api_HostAddress}}/wallets/e787d809-dd8f-4915-b97c-e7d4e94aa700

### Get wallet activities
GET {{TransferFlow.Api_HostAddress}}/wallets/8724a295-842d-4343-a99c-5f8bfa1ecdfa/activities

### Create transfer

POST {{TransferFlow.Api_HostAddress}}/transfers
Content-Type: application/json
Idempotency-Key: 7b2b4e5a-1234-4bc3-a81d-8888cf34aa01
X-Correlation-ID: 11111111-1111-1111-1111-111111111111

{
  "sourceWalletId": "f2ee139a-737b-4726-98d0-3eaebce92a73",
  "destinationWalletId": "e787d809-dd8f-4915-b97c-e7d4e94aa700",
  "amount": 30.00
}

### Get transfer
GET {{TransferFlow.Api_HostAddress}}/transfers/51fe5e2f-58c7-4e0d-942b-87b335218876
