// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransferFlow.Infrastructure.Persistence;

#nullable disable

namespace TransferFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransferFlowDbContext))]
    partial class TransferFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransferFlow.Domain.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.HasKey("Id");

                    b.ToTable("wallets", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallets_balance_non_negative", "\"balance\" >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
